{{- /* Node Metrics Collector Template */ -}}
{{- include "otel-collectors.runValidations" . -}}
{{- $name := "node-metrics" }}
{{- $collector := index .Values.collectors $name }}
{{- if and $collector.enabled (eq $collector.type "infrastructure") (eq $name "node-metrics") }}
{{- /* Merge collectorsCommon with individual collector settings */ -}}
{{- $mergedCollector := deepCopy $.Values.collectorsCommon | mustMergeOverwrite (deepCopy $collector) }}
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "otel-collectors.labels" $ | nindent 4 }}
    component: {{ $name }}
    type: {{ $mergedCollector.type }}
spec:
  image: {{ $mergedCollector.image.repository }}:{{ $mergedCollector.image.tag }}
  {{- if gt ($mergedCollector.replicas | int) 1 }}
  replicas: {{ $mergedCollector.replicas }}
  {{- end }}
  resources:
    {{- toYaml $mergedCollector.resources | nindent 4 }}
  
  # Security Configuration
  podSecurityContext:
    {{- toYaml $.Values.security.podSecurityContext | nindent 4 }}
  securityContext:
    {{- toYaml $.Values.security.containerSecurityContext | nindent 4 }}
  
  # Host network setting
  hostNetwork: {{ $.Values.security.advanced.hostNetwork }}
  
  # Pod annotations for security profiles
  {{- if $.Values.security.advanced.annotations }}
  podAnnotations:
    {{- toYaml $.Values.security.advanced.annotations | nindent 4 }}
  {{- end }}
  
  # Volume mounts for read-only root filesystem
  volumeMounts:
    - name: tmp
      mountPath: /tmp
    - name: cache  
      mountPath: /cache
    - name: data
      mountPath: /var/lib/otelcol
  volumes:
    - name: tmp
      emptyDir:
        sizeLimit: 100Mi
    - name: cache
      emptyDir:
        sizeLimit: 100Mi  
    - name: data
      emptyDir:
        sizeLimit: 1Gi
  config:
    receivers:
      {{- if has "kubeletstats" $mergedCollector.config.receivers }}
      kubeletstats:
        collection_interval: 20s
        auth_type: serviceAccount
        endpoint: ${env:K8S_NODE_NAME}:10250
        insecure_skip_verify: true
        extra_metadata_labels:
          - container.id
          - k8s.volume.type
        metric_groups:
          - container
          - pod
          - node
          - volume
      {{- end }}
      {{- if has "prometheus" $mergedCollector.config.receivers }}
      prometheus:
        config:
          scrape_configs:
          - job_name: 'integrations/node_exporter'
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
              action: keep
              regex: nodeExporter
            - source_labels: [__meta_kubernetes_pod_container_port_name]
              action: keep
              regex: metrics
            - source_labels: [__meta_kubernetes_pod_node_name]
              action: replace
              target_label: instance
            metric_relabel_configs:
            - source_labels: [__name__]
              action: keep
              regex: {{ include "otel-collectors.nodeExporterRegex" $ }}
      {{- end }}
    
    processors:
      {{- if has "memory_limiter" $collector.config.processors }}
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 25
      {{- end }}
      {{- if has "filter/kubeletstats_allowlist" $mergedCollector.config.processors }}
      filter/kubeletstats_allowlist:
        metrics:
          include:
            match_type: regexp
            metric_names:
            - "{{ include "otel-collectors.kubeletstatsRegex" $ }}"
      {{- end }}
      {{- if has "resource" $collector.config.processors }}
      resource:
        attributes:
        - key: cluster
          value: {{ $.Values.global.clusterName }}
          action: insert
        - key: workloadName
          value: {{ $mergedCollector.config.workloadName | quote }}
          action: insert
      {{- end }}
      {{- if has "batch" $mergedCollector.config.processors }}
      batch:
        send_batch_size: 1000
        timeout: 10s
      {{- end }}
    
    exporters:
      {{- range $destName, $dest := $.Values.otlpDestinations }}
      {{- if $dest.enabled }}
      otlphttp/{{ $destName }}:
        endpoint: {{ $dest.endpoint }}
        auth:
          authenticator: basicauth/{{ $destName }}
      {{- end }}
      {{- end }}
    
    extensions:
      {{- range $destName, $dest := $.Values.otlpDestinations }}
      {{- if $dest.enabled }}
      basicauth/{{ $destName }}:
        client_auth:
          username: ${env:{{ upper $destName }}_USERNAME}
          password: ${env:{{ upper $destName }}_PASSWORD}
      {{- end }}
      {{- end }}
      health_check:
        endpoint: 0.0.0.0:13133
    
    service:
      extensions: [{{- $extensions := list -}}
      {{- range $destName, $dest := $.Values.otlpDestinations -}}
        {{- if $dest.enabled -}}
          {{- $extensions = append $extensions (printf "basicauth/%s" $destName) -}}
        {{- end -}}
      {{- end -}}
      {{- $extensions = append $extensions "health_check" -}}
      {{- join ", " $extensions }}]
      pipelines:
        metrics:
          receivers: {{ $mergedCollector.config.receivers | toJson }}
          processors: {{ $mergedCollector.config.processors | toJson }}
          exporters: [{{- $metricExporters := list -}}
          {{- range $destName, $dest := $.Values.otlpDestinations -}}
            {{- if and $dest.enabled (has "metrics" $dest.signals) -}}
              {{- $metricExporters = append $metricExporters (printf "otlphttp/%s" $destName) -}}
            {{- end -}}
          {{- end -}}
          {{- join ", " $metricExporters }}]
      telemetry:
        logs:
          level: INFO

  env:
  - name: CLUSTER_NAME
    value: {{ $.Values.global.clusterName }}
  - name: COLLECTOR_ENVIRONMENT
    value: {{ $.Values.global.environment }}
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  {{- range $destName, $dest := $.Values.otlpDestinations }}
  {{- if $dest.enabled }}
  - name: {{ upper $destName }}_USERNAME
    valueFrom:
      secretKeyRef:
        key: {{ $dest.usernameKey }}
        name: {{ $dest.authSecretName }}
  - name: {{ upper $destName }}_PASSWORD
    valueFrom:
      secretKeyRef:
        key: {{ $dest.passwordKey }}
        name: {{ $dest.authSecretName }}
  {{- end }}
  {{- end }}

  volumeMounts:
  {{- if $mergedCollector.volumeMounts }}
    {{- toYaml $mergedCollector.volumeMounts | nindent 2 }}
  {{- end }}
  - name: proc
    mountPath: /host/proc
    readOnly: true
  - name: sys
    mountPath: /host/sys
    readOnly: true
    
  volumes:
  {{- if $mergedCollector.volumes }}
    {{- toYaml $mergedCollector.volumes | nindent 2 }}
  {{- end }}
  - name: proc
    hostPath:
      path: /proc
  - name: sys
    hostPath:
      path: /sys

  mode: {{ $mergedCollector.mode }}
  serviceAccount: {{ $mergedCollector.serviceAccount }}
{{- end }}