{{- /* Cluster Metrics Collector Template */ -}}
{{- include "otel-collectors.runValidations" . -}}
{{- $name := "cluster-metrics" }}
{{- $collector := index .Values.collectors $name }}
{{- if and $collector.enabled (eq $collector.type "infrastructure") (eq $name "cluster-metrics") }}
{{- /* Merge collectorsCommon with individual collector settings */ -}}
{{- $mergedCollector := deepCopy $.Values.collectorsCommon | mustMergeOverwrite (deepCopy $collector) }}
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "otel-collectors.labels" $ | nindent 4 }}
    component: {{ $name }}
    type: {{ $mergedCollector.type }}
spec:
  image: {{ $mergedCollector.image.repository }}:{{ $mergedCollector.image.tag }}
  {{- if gt ($mergedCollector.replicas | int) 1 }}
  replicas: {{ $mergedCollector.replicas }}
  {{- end }}
  resources:
    {{- toYaml $mergedCollector.resources | nindent 4 }}
  {{- if has "prometheus" $mergedCollector.config.receivers }}
  targetAllocator:
    enabled: true
  {{- end }}

  # Health Checks
  {{- if $.Values.healthChecks.livenessProbe.enabled }}
  livenessProbe:
    {{- toYaml (omit $.Values.healthChecks.livenessProbe "enabled") | nindent 4 }}
  {{- end }}
  {{- if $.Values.healthChecks.readinessProbe.enabled }}
  readinessProbe:
    {{- toYaml (omit $.Values.healthChecks.readinessProbe "enabled") | nindent 4 }}
  {{- end }}

  # Security Configuration
  podSecurityContext:
    {{- toYaml $.Values.security.podSecurityContext | nindent 4 }}
  securityContext:
    {{- toYaml $.Values.security.containerSecurityContext | nindent 4 }}
  
  # Host network setting
  hostNetwork: {{ $.Values.security.advanced.hostNetwork }}
  
  # Pod annotations for security profiles
  {{- if $.Values.security.advanced.annotations }}
  podAnnotations:
    {{- toYaml $.Values.security.advanced.annotations | nindent 4 }}
  {{- end }}
  
  # Volume mounts for read-only root filesystem
  volumeMounts:
    - name: tmp
      mountPath: /tmp
    - name: cache  
      mountPath: /cache
    - name: data
      mountPath: /var/lib/otelcol
  volumes:
    - name: tmp
      emptyDir:
        sizeLimit: 100Mi
    - name: cache
      emptyDir:
        sizeLimit: 100Mi  
    - name: data
      emptyDir:
        sizeLimit: 1Gi
  config:
    receivers:
      {{- if has "k8s_cluster" $mergedCollector.config.receivers }}
      k8s_cluster:
        auth_type: serviceAccount
        collection_interval: 10s
        node_conditions_to_report:
          - Ready
          - MemoryPressure
          - DiskPressure
          - PIDPressure
        distribution: kubernetes
        allocatable_types_to_report:
          - cpu
          - memory
          - ephemeral-storage
      {{- end }}
      {{- if has "prometheus" $mergedCollector.config.receivers }}
      prometheus:
        config:
          scrape_configs:
          - job_name: 'integrations/kubernetes/cadvisor'
            scheme: https
            tls_config:
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            kubernetes_sd_configs:
            - role: node
            relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/$${1}/proxy/metrics/cadvisor
            metric_relabel_configs:
            - source_labels: [__name__]
              action: keep
              regex: {{ include "otel-collectors.cadvisorRegex" $ }}
          - job_name: 'integrations/kubernetes/kubelet'
            scheme: https
            tls_config:
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            kubernetes_sd_configs:
            - role: node
            relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/$${1}/proxy/metrics
            metric_relabel_configs:
            - source_labels: [__name__]
              action: keep
              regex: {{ include "otel-collectors.kubeletRegex" $ }}
          - job_name: 'integrations/kubernetes/kube-state-metrics'
            kubernetes_sd_configs:
            - role: service
            relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              action: keep
              regex: .*kube-state-metrics.*
            - source_labels: [__meta_kubernetes_service_port_name]
              action: keep
              regex: http
            metric_relabel_configs:
            - source_labels: [__name__]
              action: keep
              regex: {{ include "otel-collectors.kubeStateMetricsRegex" $ }}
          - job_name: 'integrations/node_exporter'
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
              action: keep
              regex: nodeExporter
            - source_labels: [__meta_kubernetes_pod_container_port_name]
              action: keep
              regex: metrics
            - source_labels: [__meta_kubernetes_pod_node_name]
              action: replace
              target_label: instance
            metric_relabel_configs:
            - source_labels: [__name__]
              action: keep
              regex: {{ include "otel-collectors.nodeExporterRegex" $ }}
      {{- end }}
    
    processors:
      {{- if has "memory_limiter" $collector.config.processors }}
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 25
      {{- end }}
      {{- if has "resource" $collector.config.processors }}
      resource:
        attributes:
        - key: cluster
          value: {{ $.Values.global.clusterName }}
          action: insert
        - key: workloadName
          value: {{ $mergedCollector.config.workloadName | quote }}
          action: insert
      {{- end }}
      {{- if has "batch" $mergedCollector.config.processors }}
      batch:
        send_batch_size: 1000
        timeout: 10s
      {{- end }}
    
    exporters:
      {{- range $destName, $dest := $.Values.otlpDestinations }}
      {{- if $dest.enabled }}
      otlphttp/{{ $destName }}:
        endpoint: {{ $dest.endpoint }}
        auth:
          authenticator: basicauth/{{ $destName }}
      {{- end }}
      {{- end }}
    
    extensions:
      {{- range $destName, $dest := $.Values.otlpDestinations }}
      {{- if $dest.enabled }}
      basicauth/{{ $destName }}:
        client_auth:
          username: ${env:{{ upper $destName }}_USERNAME}
          password: ${env:{{ upper $destName }}_PASSWORD}
      {{- end }}
      {{- end }}
      health_check:
        endpoint: 0.0.0.0:13133
    
    service:
      extensions: [{{- $extensions := list -}}
      {{- range $destName, $dest := $.Values.otlpDestinations -}}
        {{- if $dest.enabled -}}
          {{- $extensions = append $extensions (printf "basicauth/%s" $destName) -}}
        {{- end -}}
      {{- end -}}
      {{- $extensions = append $extensions "health_check" -}}
      {{- join ", " $extensions }}]
      pipelines:
        metrics:
          receivers: {{ $mergedCollector.config.receivers | toJson }}
          processors: {{ $mergedCollector.config.processors | toJson }}
          exporters: [{{- $metricExporters := list -}}
          {{- range $destName, $dest := $.Values.otlpDestinations -}}
            {{- if and $dest.enabled (has "metrics" $dest.signals) -}}
              {{- $metricExporters = append $metricExporters (printf "otlphttp/%s" $destName) -}}
            {{- end -}}
          {{- end -}}
          {{- join ", " $metricExporters }}]
      telemetry:
        logs:
          level: INFO

  env:
  - name: CLUSTER_NAME
    value: {{ $.Values.global.clusterName }}
  - name: COLLECTOR_ENVIRONMENT
    value: {{ $.Values.global.environment }}
  {{- if and $mergedCollector.targetAllocator $mergedCollector.targetAllocator.enabled (has "prometheus" $mergedCollector.config.receivers) }}
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  {{- end }}
  {{- range $destName, $dest := $.Values.otlpDestinations }}
  {{- if $dest.enabled }}
  {{- $secretName := $dest.authSecretName | default (printf "%s-secret" $destName) }}
  {{- $usernameKey := $dest.usernameKey | default "username" }}
  {{- $passwordKey := $dest.passwordKey | default "password" }}
  - name: {{ upper $destName }}_USERNAME
    valueFrom:
      secretKeyRef:
        key: {{ $usernameKey | quote }}
        name: {{ $secretName }}
  - name: {{ upper $destName }}_PASSWORD
    valueFrom:
      secretKeyRef:
        key: {{ $passwordKey | quote }}
        name: {{ $secretName }}
  {{- end }}
  {{- end }}

  {{- if $mergedCollector.volumeMounts }}
  volumeMounts:
    {{- toYaml $mergedCollector.volumeMounts | nindent 2 }}
  {{- end }}
    
  {{- if $mergedCollector.volumes }}
  volumes:
    {{- toYaml $mergedCollector.volumes | nindent 2 }}
  {{- end }}

  mode: {{ $mergedCollector.mode }}
  serviceAccount: {{ $mergedCollector.serviceAccount }}
{{- end }}